/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        bg_shade: "#EEEFFB",
        grey_text: "#151875",
        accent: "#FB2E86",
        white: "#FFFFFF",
        liner_bg: "#F3F9FF",
        ugsadug: "#9F63B5",
        sky: "#1389FF",
        text: "#151875",
        sky_blue: "#00C1FE",
        section_hover: "#2F1AC4",
        sale_tage_color: "#3F509E",
        price_tag_color: "#FB2448",
        violet: "#7E33E0",
        oran: "#FB923C",
        sub_text_color: "#F1F0FF",
        sub_text_color2: "#8A8FB9",
        page_button_color: "#E0D3F5",
        pink: "#FB2E86",
        bg_card: "#F6F7FB",
        title_color: "#1A0B5B",
        bg_product: "#F7F7F7",
        bg_pink: "#F6F5FF",
        greeng: "#07a11b",
      },
    },
  },
  plugins: [],
};
